apiVersion: apps/v1
kind: Deployment
metadata:
  name: aletheia-service
spec:
  selector:
    matchLabels:
      app: aletheia-service
  template:
    metadata:
      labels:
        app: aletheia-service
    spec:
      containers:
      - name: aletheia-service
        image: rsamf/aletheia:latest
        ports:
        - containerPort: 5000
